# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a343a26fb1de31a3b49c3753f3e02e57811e014b9bed53379de2cc688a3503243a8ba6f22570bcc4d4d5eb0d4083e267855282de15da97b1086874754d26566

test:
  secret_key_base: 1d52f5a1fb36df8f1e846000cb0b54e726778980275191156f4340bc3a8ffa6b3d2776aaa1e15526e37a4b02b076eb92291516fea51544edb6c6bff770c6973e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
